# Generated by Django 4.2.2 on 2023-11-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_product_alter_sliders_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='uploads/staff.profile.jpg', upload_to='uploads/staff')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='sliders',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
