# Generated by Django 4.2.2 on 2023-11-05 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='msg',
            new_name='message',
        ),
    ]
